### ISSUE TITLE
Add XML parser

### ISSUE THREAD

**Issue by DrStS** [DrStS/EVAA#10]

**Comment by teo2605** [comment]
assign it to le-raffael (add him to the GitHub project too)

**Comment by DrStS** [comment]
Please use the Apache parser (STACCATO has an example). Feel free to call before you start... ;)

**Comment by khatrishubham88** [comment]
Implemented commit #[2fb1bb5](https://github.com/DrStS/EVAA/commit/2fb1bb5f92fe4cd0003b3fe08075ff65114779a7)
