### ISSUE TITLE
Add Blaze vs Eigen vs MKL (4 DOFs and 7 DOFs) with BE

### ISSUE THREAD

**Issue by DrStS** [DrStS/EVAA#2]

**Comment by teo2605** [comment]
Implemented:
- Blaze Vs. Eigen Vs. MKL - 3 DOF
- Blaze Vs. Eigen - 11 DOF

MKL for 11 DOF explodes - possible problem: ROW_MAJOR Vs. COLUMN_MAJOR:
    - for 3DOF - we use COLUMN_MAJOR - it works!
    - for 11DOF - when using ROW_MAJOR it doesn't explode anymore, but wrong results (only first element non-zero). Still working.

**Comment by teo2605** [comment]
Fixed and merged into **opensource** branch.
